namespace DeadworksManaged.Api;

/// <summary>
/// The SDK's pinned default for the <c>dwhost</c> bundle - url and SHA-256 of
/// the officially published build, so plugins work with no bundle config at
/// all. GENERATED by examples/ui/build_bundle.py; do not edit by hand -
/// rebuild the bundle instead (its bundle.json points here).
/// </summary>
public static class UiHostBundle
{
	/// <summary>The app id panels announce with.</summary>
	public const string Id = "dwhost";

	/// <summary>Where the officially published build is served from.</summary>
	public const string Url = "https://glutensnake.com/ui/dwhost_fb5f22e2.vpk";

	/// <summary>SHA-256 of that build; clients refuse anything else.</summary>
	public const string Sha256 = "fb5f22e27611b5e82b348abb6aa564fa4da0f29418b752464d2a9c10c2a5000a";

	/// <summary>A ready-to-publish bundle pinned to the official build.</summary>
	public static UiBundle Create() => new()
	{
		Id = Id,
		Url = Url,
		Sha256 = Sha256,
		CacheKeys = [@"panorama\layout\hud_health.xml"],
	};
}
